import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import {
    ServersAndPCSchema,
    PCEnum,
    TagEnum,
} from '../types/serversAndPCShema';

const initialState: ServersAndPCSchema = [
    {
        name: 'Сервер 1',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел IT',
        inventoryNumber: '12345',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-01-01',
        dateUpdate: '2023-02-01',
        dateAudit: '2023-03-01',
    },
    {
        name: 'Сервер 2',
        type: PCEnum.type2,
        location: 'Санкт-Петербург',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '67890',
        tags: [TagEnum.greenTag],
        dateCreation: '2023-02-15',
        dateUpdate: '2023-03-10',
        dateAudit: '2023-03-20',
    },
    {
        name: 'Сервер 3',
        type: PCEnum.type3,
        location: 'Киров',
        organizationUnit: 'Отдел сетей',
        inventoryNumber: '54321',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-03-05',
        dateUpdate: '2023-03-15',
        dateAudit: '2023-03-25',
    },
    {
        name: 'Сервер 4',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
    {
        name: 'Сервер 5',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел IT',
        inventoryNumber: '12345',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-01-01',
        dateUpdate: '2023-02-01',
        dateAudit: '2023-03-01',
    },
    {
        name: 'Сервер 6',
        type: PCEnum.type2,
        location: 'Санкт-Петербург',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '67890',
        tags: [TagEnum.greenTag],
        dateCreation: '2023-02-15',
        dateUpdate: '2023-03-10',
        dateAudit: '2023-03-20',
    },
    {
        name: 'Сервер 7',
        type: PCEnum.type3,
        location: 'Киров',
        organizationUnit: 'Отдел сетей',
        inventoryNumber: '54321',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-03-05',
        dateUpdate: '2023-03-15',
        dateAudit: '2023-03-25',
    },
    {
        name: 'Сервер 8',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
    {
        name: 'Сервер 9',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел IT',
        inventoryNumber: '12345',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-01-01',
        dateUpdate: '2023-02-01',
        dateAudit: '2023-03-01',
    },
    {
        name: 'Сервер 10',
        type: PCEnum.type2,
        location: 'Санкт-Петербург',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '67890',
        tags: [TagEnum.greenTag],
        dateCreation: '2023-02-15',
        dateUpdate: '2023-03-10',
        dateAudit: '2023-03-20',
    },
    {
        name: 'Сервер 11',
        type: PCEnum.type3,
        location: 'Киров',
        organizationUnit: 'Отдел сетей',
        inventoryNumber: '54321',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-03-05',
        dateUpdate: '2023-03-15',
        dateAudit: '2023-03-25',
    },
    {
        name: 'Сервер 12',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
    {
        name: 'Сервер 13',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел IT',
        inventoryNumber: '12345',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-01-01',
        dateUpdate: '2023-02-01',
        dateAudit: '2023-03-01',
    },
    {
        name: 'Сервер 14',
        type: PCEnum.type2,
        location: 'Санкт-Петербург',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '67890',
        tags: [TagEnum.greenTag],
        dateCreation: '2023-02-15',
        dateUpdate: '2023-03-10',
        dateAudit: '2023-03-20',
    },
    {
        name: 'Сервер 15',
        type: PCEnum.type3,
        location: 'Киров',
        organizationUnit: 'Отдел сетей',
        inventoryNumber: '54321',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-03-05',
        dateUpdate: '2023-03-15',
        dateAudit: '2023-03-25',
    },
    {
        name: 'Сервер 16',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
    {
        name: 'Сервер 17',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел IT',
        inventoryNumber: '12345',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-01-01',
        dateUpdate: '2023-02-01',
        dateAudit: '2023-03-01',
    },
    {
        name: 'Сервер 18',
        type: PCEnum.type2,
        location: 'Санкт-Петербург',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '67890',
        tags: [TagEnum.greenTag],
        dateCreation: '2023-02-15',
        dateUpdate: '2023-03-10',
        dateAudit: '2023-03-20',
    },
    {
        name: 'Сервер 19',
        type: PCEnum.type3,
        location: 'Киров',
        organizationUnit: 'Отдел сетей',
        inventoryNumber: '54321',
        tags: [TagEnum.redTag, TagEnum.blueTag],
        dateCreation: '2023-03-05',
        dateUpdate: '2023-03-15',
        dateAudit: '2023-03-25',
    },
    {
        name: 'Сервер 20',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
    ,
    {
        name: 'Сервер 21',
        type: PCEnum.type1,
        location: 'Москва',
        organizationUnit: 'Отдел разработки',
        inventoryNumber: '98765',
        tags: [TagEnum.redTag],
        dateCreation: '2023-01-10',
        dateUpdate: '2023-02-20',
        dateAudit: '2023-03-30',
    },
];

export const serversAndPCSlice = createSlice({
    name: 'serversAndPC',
    initialState,
    reducers: {
        setServersAndPCs: (
            state,
            action: PayloadAction<ServersAndPCSchema>
        ) => {
            return action.payload;
        },
    },
});

export const { actions: serversAndPCActions } = serversAndPCSlice;
export const { reducer: serversAndPCReducer } = serversAndPCSlice;
